version: '3.3'
services:
  php74:
    build:
      context: docker
      dockerfile: Dockerfile
    ports:
      - 8086:80
    working_dir: /app
    volumes:
      - ./parisSportifCode/app
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE:
    ports:
      - "3308:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
  composer:
    restart: always
    image: composer
    command: install
    working_dir: /app
    volumes:
      - ./parisSportifCode:/app
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025