version: '3'

services:
  traefik:
    image: "traefik"
    restart: "always"
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
    ports:
      - "8080:8080"
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - proxy

  php7.4:
    container_name: php7.4
    build: ./docker/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`php.docker.localhost`)"
    volumes:
      - "./parisSportifCode:/var/www/html/"
    environment:
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: "1"
      PHP_OPCACHE_MAX_ACCELERATED_FILES: "10000"
      PHP_OPCACHE_MEMORY_CONSUMPTION: "192"
      PHP_OPCACHE_MAX_WASTED_PERCENTAGE: "10"
    networks:
      - proxy

  composer:
    image: "composer"
    restart: "no"
    working_dir: "/app"
    command: "install"
    volumes:
      - "./parisSportifCode:/app"

  db:
    image: mysql
    restart: on-failure
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - "./db/:/var/lib/mysql/"
    networks:
      - proxy


  phpmyadmin:
    image: "phpmyadmin"
    environment:
      PMA_HOST: "db"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`pma.docker.localhost`)"
    networks:
      - proxy

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailhog.rule=Host(`mho.docker.localhost`)"
      - "traefik.services.mailhog.loadbalancer.server.port=8025"
    networks:
      - proxy

networks:
  proxy:
    name: proxy