version: '3'
services:
  traefik:
    image: "traefik"
    restart: "always"
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
    ports:
      - "8080:8080"
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  ## php container
  php-apache:
    build:
      context: docker
      dockerfile: Dockerfile
    image: hello-world-demo
    restart: "always"
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php.rule=Host(`php.docker.localhost`)"
    volumes:
      - ./parisSportifCode:/app
  #    depends_on:
  #      - db
  ## composer container
  composer:
    image: composer
    restart: "no"
    command: install
    working_dir: /app
    volumes:
      - ./parisSportifCode:/app

  ## mysql container
  db:
    #container_name: "db"
    image: "mysql"
    restart: "always"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./mysql-data:/var/lib/mysql

  ## phpMyAdmin container
  phpmyadmin:
    #container_name: "phmyadmin"
    image: "phpmyadmin"
    environment:
      PMA_HOST: "db"
    labels:
      - "traefik.http.routers.phpmyadmin.rule=Host(`pma.docker.localhost`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=web"

  ## mailhog container
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    labels:
      - "traefik.http.routers.mailhog.rule=Host(`mho.docker.localhost`)"
      - "traefik.http.routers.mailhog.entrypoints=web"
      - "trafik.services.mailhog.loadbalancer.server.port=8025"