@startuml

class Utilisateur {
    - Id integer
    - Nom string
    - Prenom stringe
    - Date de naissance date
    - Adress string
    - Pays string
    - Ville string
    - Telephone number
    - Email string
    - Mot_de_passe integer
    - IdStatut StatutUtilisateur
    - Solde float


}
class StatutUtilisateur {
    - id integer
    - Document_Officelle Bloob
    - Statut <0,1>
}

class Transaction {
    - id integer
    - IdUtilisateur
    - Dernnier_solde_mis integer
    - Dernnier_solde_sorti integer
}

class Pari {
    - Id
    - IdPronostic
    - IdUtilisateur
    - Date date
    - mise float
    - solde float
}


class Pronostic {
    - Nom string
    - Cote float
}

class Epreuve {
    - id integer
    - Nom string
    - Date date
    - Lieu string
    - idEvenement Evenement
}

class Evenement {
    - id integer
    - Nom string
    - Date_Debut
}

class Sport {
    - Nom string
}
class SportCollectif {
    - Nombre_joueurs
}
class Equipe {
    - id integer
    - Nom Equipe
}
class Joueurs {
    - Nom string
    - Prenom string
    - Statut string
}

class SportIndivesuelle {
    - Nom_joueur string
    - Prenom_joueur string
    - Statut string
}
class HistoriquePari {
    - id integer
    - IdUtilisateur integer
    - Date date date
    - mise float
    - solde float
}


(Utilisateur, Pronostic) . Pari
Utilisateur "1" *-- "0..*" Transaction
Utilisateur "1" *-- "1" StatutUtilisateur
Pronostic "0..*" --* "1" Epreuve
Epreuve "0..*" --* "1" Evenement
Evenement "0..*" --* "1" Sport
Pronostic "0..*" -- "1" Evenement
Sport <|-- SportIndivesuelle
Sport <|-- SportCollectif
SportCollectif "1" -- "1..*" Equipe
Equipe "1" -- "1..*" Joueurs
Pari -- HistoriquePari

@enduml
