@startuml
class Parieur
class Pari
class Cote
class Epreuve
class Evenement
class Sport

Parieur "1" *-- "0..*" Pari
Parieur "1" -- "1" Portefeuille
Pari "0..*" -- "1" Portefeuille
Pari "0..*" --* "1" Cote
Cote "0..*" --* "1" Epreuve
Epreuve "0..*" --* "1" Evenement
Evenement "0..*" --* "1" Sport
Sport "1"*--"1..*" Equipe
Sport "1" *--"1..*" JoueurIndividuel
Equipe "1" *-- "1..*" Joueur

class Parieur {
    - Nom string
    - Prenom stringe
    - Date de naissance date
    - Adress string
    - Pays string
    - Ville string
    - Telephone number
    - Email string

    + getNom()
    + getPrenom()
    + getDateDeNassance()
    + getAdresse()
    + getpays()
    + getville()
    + gettelephone()
    + getemail()
    + setNom()
    + setPrenom()
    + setDateDeNassance()
    + setAdresse()
    + setpays()
    + setville()
    + settelephone()
    + setemail()

}

class Pari {
    - Date date
    - Type string
    - Mise float
    - Solde float

    + getDate()
    + getType()
    + getMise()
    + getSolde()
    + setDate()
    + setType()
    + setMise()
    + setSolde()
}
class Portefeuille {
    - solde float
    - idPari integer
    - idutilisateur integer
    - statut string
    
    + getSolde()
    + setSolde()
    + getidPari()
    + getidutilisateur()
    + getstatut()
    + settidPari()
    + setidutilisateur()
    + setstatut()

}

class Cote {
    - Nom string
    - Cote float

    + getNom()
    + getCote()
    + setNom()
    + setCote()
}

class Epreuve {
    - Nom string
    - Date date
    - Lieu string

    + getNom()
    + getDate()
    + getLieu()
    + setNom()
    + setDate()
    + setLieu()


}

class Evenement {
    - Nom string

    +getNom()
    +setNom()
}

class Sport {
    - Nom string
    - Type string

    + getNom()
    + getType()
    + setNom()
    + setType()

}
class Equipe {
    - Nom string

    + getNom()
    + setNom()
}
class Joueur {
    - Nom string
    - Prenom
    - Statut

    + getNom()
    + setNom()
    + getPrenom()
    + setPrenom()
    + getStatut()
    + setStatut()

}
class JoueurIndividuel {
    - Nom string
    - Prenom string
    - statut integer

    + getNom()
    + setNom()
    + getPrenom()
    + setPrenom()
    + getStatut()
    + setStatut()

}


@enduml
