name: CI

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: rtestT
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
      
    steps:

      - uses: actions/checkout@v1
      - name: Run Composer
        run: |
          cd parisSportifCode
          composer install --prefer-dist
      - name: MySQL connection
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client
          mysql --host 127.0.0.1 --port 3306 -uroot -e "SHOW DATABASES"
      - name: Load tables and fixtures
          cd parisSportifCode
          cp -r .env.test .env
          php bin/console doctrine:schema:update --env=test --force
          php bin/console doctrine:fixtures:load --env=test --no-interaction
      - name: Run phpunit
        run: |
          cd parisSportifCode
          ./vendor/bin/simple-phpunit