# On définit le nom de l'action
name: Deploy Test Unitaire sur le push

# sur quelle action notre evenement se déclenche
# ici sur le push dans la branche main et sur la pull request
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# on définit ici la ou les les taches que notre action doit faire
jobs:
  build-test:
    runs-on: unbuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@main
      - name: PHPUnit Tests
          uses: php-actions/phpunit@17-php-versions
          with:
            UserTest: vendor/autoload.php
            configuration: test/phpunit.xml
            args: --coverage-text

