name: Class User test
on:
  push:
    branches: [ feature/create_entity_Test ]

jobs:
  build-test:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v1
      - name: Run Composer
        run: |
          cd parisSportifCode
          composer install --prefer-dist
      - name: Run phpunit
        run: |
          cd parisSportifCode
          ./vendor/bin/simple-phpunit